### ISSUE TITLE
Test Account: Tikitoo1, password:abc123456

### ISSUE THREAD

**Issue by MrFuFuFu** [Tikitoo/Diigoer#1]
Test Account: Tikitoo1, password:abc123456 不能用

**Comment by Tikitoo** [comment]
因为之前测试的就有点小问题，您可以多点击几次，应该可以登录。

**Comment by 314086511hello** [comment]
您好，这个安装包还有吗，我在学这个代码，可以给我一个安装包试一下吗

**Comment by Tikitoo** [comment]
> 您好，这个安装包还有吗，我在学这个代码，可以给我一个安装包试一下吗

现在这个项目不推荐使用了，可以在Github 搜一搜其他的项目
